preload = ~/Pictures/Wallpapers/ichigo.jpg
# If more than one preload is desired then continue to preload other backgrounds
#preload = /path/to/next_image.png
# .. more preloads

# Set the default wallpaper for every monitor.
wallpaper = ,~/Pictures/Wallpapers/ichigo.jpg

# If a monitor needs a different image, add a more specific rule, for example:
# wallpaper = HDMI-1,/path/to/image.png
# .. more monitors
